extends "res://addons/gut/test.gd"

# Procedural Algorithm Audit & Documentation Generator
# This "test" runs simulations to generate a Markdown overview of core algorithms.

const SIM_COUNT = 1000
const AUDIT_FILE = "ALGORITHMS_OVERVIEW.md"

func _calculate_ascent(run_data: Dictionary) -> float:
	var total_ascent = 0.0
	for e in run_data["edges"]:
		for s in e["profile"]["segments"]:
			if s["grade"] > 0:
				total_ascent += s["distanceM"] * s["grade"]
	return total_ascent

func _get_stats(values: Array) -> Dictionary:
	values.sort()
	var sum = 0.0
	for v in values: sum += v
	var mean = sum / values.size()
	var median = values[values.size() / 2]
	var min_val = values[0]
	var max_val = values[values.size() - 1]
	# Simple outlier detection (Q1 - 1.5*IQR or Q3 + 1.5*IQR)
	var q1 = values[int(values.size() * 0.25)]
	var q3 = values[int(values.size() * 0.75)]
	var iqr = q3 - q1
	var low_outliers = []
	var high_outliers = []
	for v in values:
		if v < q1 - 1.5 * iqr: low_outliers.append(v)
		if v > q3 + 1.5 * iqr: high_outliers.append(v)
	
	return {
		"mean": mean,
		"median": median,
		"min": min_val,
		"max": max_val,
		"high_outlier": high_outliers.size() > 0
	}

func test_generate_algorithm_overview():
	var md = "# Spokes: Core Algorithms & Procedural Overview\n\n"
	md += "This document is automatically generated by running the `tests/test_audit.gd` suite. "
	md += "It provides a statistical breakdown of procedural generation across %d simulations per configuration.\n\n" % SIM_COUNT
	
	md += "## 1. Map Generation (`MapGenerator.gd`)\n"
	md += "The Hub-and-Spoke generator creates a radial map where each 'spoke' represents a biome/level. "
	md += "Difficulty scales the base grade, hazard impact, and random variance.\n\n"
	
	var distances = [50.0, 200.0]
	var difficulties = ["easy", "normal", "hard"]
	
	md += "### Elevation and Distance Stats\n\n"
	md += "| Target | Diff | Metric | Mean | Median | Min | Max | Outliers? |\n"
	md += "| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |\n"
	
	var all_node_types = {}
	
	for dist in distances:
		for diff in difficulties:
			var ascent_results = []
			var dist_results = []
			
			for i in range(SIM_COUNT):
				var run_data = {
					"totalDistanceKm": dist,
					"difficulty": diff,
					"stats": {"totalMapDistanceM": 0.0},
					"nodes": [], "edges": [], "visitedNodeIds": [], "currentNodeId": ""
				}
				MapGenerator.generate_hub_and_spoke_map(run_data)
				
				var actual_km = run_data["stats"]["totalMapDistanceM"] / 1000.0
				var total_ascent_m = _calculate_ascent(run_data)
				var ft_per_10mi = (total_ascent_m / (actual_km * 1000.0)) * 16093.44 * 3.28084
				
				ascent_results.append(ft_per_10mi)
				dist_results.append(actual_km)
				
				# Count node types (only for one distance to keep it simple)
				if dist == 200.0 and diff == "normal":
					for node in run_data["nodes"]:
						var t = node["type"]
						all_node_types[t] = all_node_types.get(t, 0) + 1
			
			var a_stats = _get_stats(ascent_results)
			var d_stats = _get_stats(dist_results)
			
			md += "| %dkm | %s | Ascent (ft/10mi) | %.1f | %.1f | %.1f | %.1f | %s |\n" % [
				dist, diff, a_stats.mean, a_stats.median, a_stats.min, a_stats.max, "Yes" if a_stats.high_outlier else "No"
			]
			md += "| | | Map Dist (km) | %.1f | %.1f | %.1f | %.1f | %s |\n" % [
				d_stats.mean, d_stats.median, d_stats.min, d_stats.max, "Yes" if d_stats.high_outlier else "No"
			]

	md += "\n### Node Type Distribution (200km Normal Run)\n\n"
	md += "| Node Type | Avg per Map | Percentage |\n"
	md += "| :--- | :--- | :--- |\n"
	for t in all_node_types:
		var avg = float(all_node_types[t]) / SIM_COUNT
		md += "| %s | %.2f | %.1f%% |\n" % [t, avg, (avg / 66.0) * 100.0] # 66 is approx nodes for 8 spokes

	md += "\n## 2. Course Profile Generation (`CourseProfile.gd`)\n"
	md += "Generates a variable elevation profile for a single edge. Each edge begins and ends flat (250m buffers). "
	md += "Middle segments vary based on target distance and max grade.\n\n"
	
	var profile_configs = [
		{"km": 5.0, "grade": 0.04},
		{"km": 20.0, "grade": 0.08}
	]
	
	md += "| Config | Metric | Mean | Median | Min | Max |\n"
	md += "| :--- | :--- | :--- | :--- | :--- | :--- |\n"
	
	for cfg in profile_configs:
		var segment_counts = []
		var avg_grades = []
		
		for i in range(SIM_COUNT):
			var p = CourseProfile.generate_course_profile(cfg.km, cfg.grade)
			segment_counts.append(p["segments"].size())
			
			var total_g = 0.0
			var count_g = 0
			for s in p["segments"]:
				if s["grade"] != 0.0:
					total_g += abs(s["grade"])
					count_g += 1
			if count_g > 0:
				avg_grades.append((total_g / count_g) * 100.0)
		
		var s_stats = _get_stats(segment_counts)
		var g_stats = _get_stats(avg_grades)
		
		md += "| %dkm @ %.0f%% | Segments | %.1f | %.1f | %.1f | %.1f |\n" % [
			cfg.km, cfg.grade * 100.0, s_stats.mean, s_stats.median, s_stats.min, s_stats.max
		]
		md += "| | Avg Grade %% | %.2f%% | %.2f%% | %.2f%% | %.2f%% |\n" % [
			g_stats.mean, g_stats.median, g_stats.min, g_stats.max
		]

	md += "\n## 3. Elite Challenges (`EliteChallenge.gd`)\n"
	md += "Elite challenges are 'Hard' nodes that present specific power-based goals. "
	md += "The following table shows the distribution of challenge types across %d selections.\n\n" % SIM_COUNT
	
	var type_counts = {}
	for i in range(SIM_COUNT):
		var c = EliteChallenge.get_random_challenge()
		var t = c["title"]
		type_counts[t] = type_counts.get(t, 0) + 1
		
	md += "| Challenge Title | Frequency | Percentage |\n"
	md += "| :--- | :--- | :--- |\n"
	for t in type_counts:
		md += "| %s | %d | %.1f%% |\n" % [t, type_counts[t], (float(type_counts[t])/SIM_COUNT)*100.0]

	# Write to file
	var file = FileAccess.open("res://" + AUDIT_FILE, FileAccess.WRITE)
	if file:
		file.store_string(md)
		file.close()
		print("Successfully generated audit overview to ", AUDIT_FILE)
	else:
		print("Failed to write audit file!")
	
	assert_file_exists("res://" + AUDIT_FILE)
